### PR TITLE
handle 0 probability in table_dist_1d

### PR DESCRIPTION
**Pull request by arthur-x**
Remove assertion failed error when handling 0 weighted components in table_dist_1d. (Code behaviors not changed since 0 weighted components will never be sampled.)

### CODE REVIEW

**Comment by BachiLi** [comment]
This is not ideal: if you have multiple lights but one of them has zero intensity, this will lead to an error but we can just not sample that light. Any particular reason why you want to do this?

**Comment by arthur-x** [comment]
Used table_dist_1d when sampling disney bsdf components. Some of the components have zero weights, adjusting this assertion makes the code simpler.

**Comment by arthur-x** [comment]
Could you elaborate on why zero-intensity lights can cause problem in this case? I thought they should be illegal in the first place (maybe another assertion elsewhere). Thanks!

**Comment by BachiLi** [comment]
I didn't use this struct when implementing BSDF component selection (I think the extra heap allocation of the std::vector makes it less ideal). You're free to use it and modify it as you wish in your code though.
Allowing light sources to have zero intensity would be useful in the case where the 3D scene is procedurally generated -- then the author of the scene only needs to clamp the light intensity to zero instead of some arbitrary small threshold. It's a small thing but I don't really see the point of changing this.

**Comment by arthur-x** [comment]
Thanks for the reply, although I still don't understand:

> the author of the scene only needs to clamp the light intensity to zero instead of some arbitrary small threshold.

In that case the original code will raise an assertion error (not allowing zero-intensity lights) but the modified code won't (allowing zero-intensity lights), right? Sorry I'm a bit confused.

**Comment by BachiLi** [comment]
OMG I am the one who is confused. I think your version is better. I'll merge this.

**Comment by BachiLi** [comment]
(sorry for the confusion btw!)

**Pull request merged**
